Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - spec/**/*
  ExcludedMethods:
    - class_methods

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  CountComments: false
  Max: 24

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Style/ModuleFunction:
  Enabled: false
