env:
  global:
    - CC_TEST_REPORTER_ID=495ac15aa01f24dcfe0b3467e5093e99c32b6b56b1cb774489edd17207631fd6

language: ruby

before_install: gem install bundler -v 2.0.2

cache: bundler

rvm:
  - 2.4.1

sudo: false

script:
  - bundle exec rake code_analysis
  - bundle exec rspec
